export const dictionary = [
    { phrase: "To move quickly and suddenly", word: "jolt" },
    { phrase: "To yell or shout loudly", word: "scream" },
    { phrase: "A rapid or loud sound", word: "blare" },
    { phrase: "A joyful shout of approval", word: "cheer" },
    { phrase: "To glance quickly at something", word: "glimpse" },
    { phrase: "To take away someone's hope", word: "wreak" },
    { phrase: "A brief look or glance", word: "flash" },
    { phrase: "To walk in a relaxed manner", word: "stroll" },
    { phrase: "To make a soft murmuring sound", word: "hum" },
    { phrase: "To intensely dislike", word: "loathe" },
    { phrase: "A loud, deep sound", word: "roar" },
    { phrase: "To stare angrily at someone", word: "glare" },
    { phrase: "To achieve victory", word: "win" },
    { phrase: "To feel a sharp pain", word: "sting" },
    { phrase: "To fall down suddenly", word: "collapse" },
    { phrase: "A small, sharp tool", word: "needle" },
    { phrase: "To move slowly or cautiously", word: "creep" },
    { phrase: "A sudden and intense burst of light", word: "flare" },
    { phrase: "To rest for a short period", word: "nap" },
    { phrase: "To hold tightly", word: "grip" },
    { phrase: "To travel to a destination", word: "journey" },
    { phrase: "A large gathering of people", word: "crowd" },
    { phrase: "To consume food quickly", word: "devour" },
    { phrase: "To feel relieved from pain or stress", word: "soothe" }
];
